include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/container_scan-v2.yml

stages:
  - base
  - extra
  - scan

variables:
  DOCKER_VERSION: 19.03.2
  DOCKER_BUILDKIT: 1

image: registry.gitlab.com/jitesoft/dockerfiles/docker:latest

build:docker:
  stage: base
  script:
    - docker --version
    - dockerd --version
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} --build-arg DOCKER_VERSION=${DOCKER_VERSION} .
    - docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} ${CI_REGISTRY_IMAGE}:${DOCKER_VERSION}
    - docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:${DOCKER_VERSION}
    - docker push ${CI_REGISTRY_IMAGE}:latest
  tags:
    - jitesoft
  only:
    refs:
      - master

build:dind:
  stage: extra
  script:
    - cd Dind
    - docker build -t ${CI_REGISTRY_IMAGE}/dind:${CI_COMMIT_SHA} --build-arg DOCKER_VERSION=${DOCKER_VERSION} .
    - docker tag ${CI_REGISTRY_IMAGE}/dind:${CI_COMMIT_SHA} ${CI_REGISTRY_IMAGE}/dind:${DOCKER_VERSION}
    - docker tag ${CI_REGISTRY_IMAGE}/dind:${CI_COMMIT_SHA} ${CI_REGISTRY_IMAGE}/dind:latest
    - docker push ${CI_REGISTRY_IMAGE}/dind:${DOCKER_VERSION}
    - docker push ${CI_REGISTRY_IMAGE}/dind:latest
  tags:
    - jitesoft
  only:
    refs:
      - master

scan:
  needs:
    - build:docker
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}:latest"
    GIT_STRATEGY: none

scan:dind:
  needs:
    - build:dind
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/dind:latest"
    GIT_STRATEGY: none
